apiVersion: batch/v1
kind: Job
metadata:
  name: nodeapp
spec:
  template:
    metadata:
      name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: alpbugra/nodeapp
        imagePullPolicy: Always
      restartPolicy: Never
