apiVersion: batch/v1
kind: Job
metadata:
  name: nodeapp
spec:
  template:
    metadata:
      name: nodeapp-pod
    spec:
      containers:
      - name: nodeapp
        image: alpbugra/nodeapp:latests
        imagePullPolicy: Always
      restartPolicy: OnFailure
