apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitterapp-deployment
  labels:
    app: twitterapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitterapp
  template:
    metadata:
      labels:
        app: twitterapp
    spec:
      containers:
      - name: twitterapp
        image: alpbugra/twitterapp:latest
        imagePullPolicy: Always
      restartPolicy: Always
