apiVersion: batch/v1
kind: Job
metadata:
  name: nodeapp
spec:
  template:
    metadata:
      name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: alpbugra/nodeapp
        restartPolicy: Never
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
